import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'yo';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.sermons': 'Sermons',
    'nav.videos': 'Videos',
    'nav.gallery': 'Gallery',
    'nav.events': 'Events',
    'nav.ministries': 'Ministries',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.give': 'Give',
    'nav.tagline': 'Faith, hope & Love.',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.followUs': 'Follow Us',
    'footer.serviceTimes': 'Service Times',
    'footer.rights': 'All rights reserved.',
    'footer.aboutUs': 'About Us',
    'footer.prayerRequests': 'Prayer Requests',
    'footer.sundayWorship': 'Sunday Worship: 8:00 AM - 10:00 AM',
    'footer.bibleStudy': 'Wednesday Bible Study: 5:00 PM - 6:00PM',
    'footer.youthGroup': 'Youth Group Fellowship: Friday 5:00 PM',
    'footer.address': '20, Michael Ibru Road, Amilegbe, P.O. Box 138, Ilorin, Nigeria.',
    
    // Common
    'common.readMore': 'Read More',
    'common.register': 'Register',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.viewAll': 'View All',
    'common.learnMore': 'Learn More',
    'common.getInvolved': 'Get Involved',
    'common.contactLeader': 'Contact Leader',
    'common.sendMessage': 'Send Message',
    'common.sending': 'Sending...',
    
    // Homepage
    'home.welcomeHome': 'Welcome Home',
    'home.welcomeText': 'Where faith grows, hearts are healed, and lives are transformed through God\'s love and community.',
    'home.watchLive': 'Watch Live',
    'home.joinUsThisWeek': 'Join Us This Week',
    'home.joinUsText': 'Come as you are and experience the love of God in our welcoming community.',
    'home.sundayWorship': 'Sunday Worship',
    'home.englishService': 'English Service: 8:00AM - 10:00AM',
    'home.yorubaService': 'Yoruba Service: 10:00AM - 12:00PM',
    'home.bibleStudy': 'Bible Study',
    'home.bibleStudyTime': 'Wednesday 5:00 PM - 6:00PM',
    'home.bibleStudyText': 'Deep dive into God\'s Word together',
    'home.youthGroup': 'Youth Group',
    'home.youthGroupTime': 'Friday 5:00 PM',
    'home.youthGroupText': 'Fun, faith, and fellowship for teens',
    'home.ourHeartMission': 'Our Heart & Mission',
    'home.missionText1': 'For over a few decades, Second ECWA has been a beacon of hope and love in our community. We believe in the transformative power of faith, the strength of community, and the importance of serving others with compassion and grace.',
    'home.missionText2': 'Whether you\'re seeking spiritual guidance, looking for a place to belong, or wanting to make a difference in the world, you\'ll find your home here with us.',
    'home.learnMore': 'Learn More About Us',
    'home.members': '500+ Members',
    'home.growingTogether': 'Growing in faith together',
    'home.getConnected': 'Get Connected',
    'home.getConnectedText': 'Explore ways to grow in faith and serve our community',
    'home.latestSermons': 'Latest Sermons',
    'home.latestSermonsText': 'Listen to recent messages and find inspiration',
    'home.upcomingEvents': 'Upcoming Events',
    'home.upcomingEventsText': 'Join us for special services and activities',
    'home.giveOnline': 'Give Online',
    'home.giveOnlineText': 'Support our mission and community outreach',
    'home.visitUs': 'Visit Us',
    'home.visitUsText': 'Find directions and plan your first visit',
    'home.thisWeekMessage': 'This Week\'s Message',
    'home.featuredSermonTitle': '"Walking in Faith, Not Fear"',
    'home.featuredSermonText': 'Join Samuel Oyegunle as he explores how faith can overcome our deepest fears and uncertainties. Discover the peace that comes from trusting in God\'s perfect plan for your life.',
    'home.scripture': 'Scripture',
    'home.scriptureRef': 'Isaiah 41:10',
    'home.date': 'Date',
    'home.sermonDate': 'May 15, 2025',
    'home.viewAllSermons': 'View All Sermons',
    'home.watchSermon': 'Watch Sermon',
    
    // About Page
    'about.title': 'About Second ECWA',
    'about.subtitle': 'For over two decades, we\'ve been a place where faith flourishes, community thrives, and lives are transformed by the love of Jesus Christ.',
    'about.ourStory': 'Our Story',
    'about.storyText1': 'Second ECWA was founded in 1974 by a small group of missionaries who shared a vision of creating a church that would be the heart of the community. What started as frequent gatherings in a room has grown into a vibrant congregation of over 500 members.',
    'about.storyText2': 'Throughout our history, we\'ve remained committed to our founding principles: authentic worship, genuine community, and compassionate service. We believe that faith is not just a Sunday morning activity, but a way of life that transforms individuals, families, and communities.',
    'about.storyText3': 'Today, we continue to be a place where people from all walks of life can find hope, healing, and purpose. Whether you\'re taking your first steps in faith or have been walking with God for years, you\'ll find a home here with us.',
    'about.yearsOfMinistry': 'Years of Ministry',
    'about.ourMission': 'Our Mission',
    'about.missionText': 'To be the heart of our community by connecting people to God, to each other, and to their purpose through authentic worship, genuine relationships, and compassionate service.',
    'about.ourVision': 'Our Vision',
    'about.visionText': 'A community where every person experiences the transformative love of Jesus Christ and is empowered to make a positive impact in the world around them.',
    'about.coreValues': 'Our Core Values',
    'about.coreValuesText': 'These values guide everything we do and shape the culture of our church community.',
    'about.love': 'Love',
    'about.loveText': 'We believe in the transformative power of God\'s unconditional love and strive to share it with everyone we meet.',
    'about.community': 'Community',
    'about.communityText': 'We foster authentic relationships and create a welcoming space where everyone belongs and can grow together.',
    'about.service': 'Service',
    'about.serviceText': 'We are called to serve our local community and beyond, making a positive impact in Jesus\' name.',
    'about.compassion': 'Compassion',
    'about.compassionText': 'We extend grace and mercy to all, offering support and care to those in need without judgment.',
    'about.leadership': 'Our Leadership Team',
    'about.leadershipText': 'Meet the dedicated leaders who serve our church community with passion and purpose.',
    'about.whatWeBelieve': 'What We Believe',
    'about.faithGrounded': 'Our faith is grounded in the timeless truths of Christianity',
    'about.bible': 'The Bible',
    'about.bibleText': 'We believe the Bible is the inspired, authoritative Word of God and our guide for faith and living.',
    'about.jesusChrist': 'Jesus Christ',
    'about.jesusText': 'We believe Jesus Christ is the Son of God, who died for our sins and rose again, offering salvation to all who believe.',
    'about.holySpirit': 'The Holy Spirit',
    'about.spiritText': 'We believe the Holy Spirit guides, empowers, and transforms believers to live according to God\'s will.',
    'about.church': 'The Church',
    'about.churchText': 'We believe the church is the body of Christ, called to worship God, fellowship together, and serve the world.',
    
    // Events Page
    'events.title': 'Upcoming Events',
    'events.subtitle': 'Join us for meaningful gatherings, special services, and community events that strengthen our faith and fellowship.',
    'events.featured': 'Featured Event',
    'events.featuredText': 'Don\'t miss this special upcoming event',
    'events.register': 'Register Now',
    'events.allEvents': 'All Events',
    'events.filterByCategory': 'Filter by Category',
    'events.registered': 'registered',
    'events.firstName': 'First Name',
    'events.lastName': 'Last Name',
    'events.email': 'Email',
    'events.phone': 'Phone',
    'events.specialNeeds': 'Special Needs/Accommodations',
    'events.emergencyContact': 'Emergency Contact',
    'events.emergencyPhone': 'Emergency Phone',
    'events.completeRegistration': 'Complete Registration',
    'events.registering': 'Registering...',
    
    // Ministries Page
    'ministries.title': 'Our Ministries',
    'ministries.subtitle': 'Discover ways to grow in faith, build community, and serve others. There\'s a place for everyone to belong and make a difference.',
    'ministries.featured': 'Featured Ministry',
    'ministries.featuredText': 'Get involved and make a meaningful impact',
    'ministries.ageGroup': 'Age Group',
    'ministries.meetingTime': 'Meeting Time',
    'ministries.location': 'Location',
    'ministries.leader': 'Leader',
    'ministries.activities': 'Activities',
    'ministries.allMinistries': 'All Ministries',
    'ministries.allMinistriesText': 'From children to seniors, from worship to outreach, find where you can serve and grow in your faith journey.',
    'ministries.volunteer': 'Volunteer',
    'ministries.position': 'Preferred Position/Role',
    'ministries.volunteerApplication': 'Submit Volunteer Application',
    'ministries.submitting': 'Submitting...',
    
    // Contact Page
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'We\'d love to hear from you! Whether you have questions, need prayer, or want to get involved, we\'re here to help.',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.openHours': 'Open Hours',
    'contact.serviceSchedule': 'Service Schedule',
    'contact.scheduleText': 'Join us for worship and fellowship throughout the week',
    'contact.sendMessage': 'Send Us a Message',
    'contact.messageText': 'Have a question or prayer request? We\'d love to hear from you. Fill out the form below and we\'ll get back to you as soon as possible.',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.findUs': 'Find Us',
    'contact.mapText': 'Can\'t see the map?',
    'contact.openInGoogleMaps': 'Open in Google Maps',
    'contact.needPrayer': 'Need Prayer?',
    'contact.prayerText': 'Our prayer team is here for you. Submit a confidential prayer request and know that our community is lifting you up in prayer.',
    'contact.prayerRequest': 'Prayer Request',
    'contact.urgent': 'This is urgent',
    'contact.confidential': 'Keep this confidential',
    'contact.submitPrayer': 'Submit Prayer Request',
    'contact.submittingPrayer': 'Submitting...',
    
    // Give Page
    'give.title': 'Give with Purpose',
    'give.subtitle': 'Your generosity helps us fulfill our mission of spreading God\'s love and serving our community with compassion and care.',
    'give.scripture': '"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver."',
    'give.scriptureRef': '- 2 Corinthians 9:7',
    'give.waysToGive': 'Ways to Give',
    'give.waysText': 'Choose the giving option that aligns with your heart and financial situation.',
    'give.tithe': 'Tithe',
    'give.titheText': 'Regular giving to support the church ministry',
    'give.titheAmount': '10% of income',
    'give.specialOffering': 'Special Offering',
    'give.offeringText': 'Support special projects and missions',
    'give.buildingFund': 'Building Fund',
    'give.buildingText': 'Help us expand our church facilities',
    'give.anyAmount': 'Any amount',
    'give.howToGive': 'How to Give',
    'give.methodsText': 'Choose your preferred method to make your donation.',
    'give.bankTransfer': 'Bank Transfer',
    'give.bankText': 'Direct bank transfer to our church account',
    'give.onlineDonation': 'Online Donation',
    'give.onlineText': 'Secure online giving via Paystack',
    'give.giveOnlineButton': 'Give Online (Coming Soon)',
    'give.yourImpact': 'Your Impact',
    'give.impactText': 'See how your generous giving helps transform lives and strengthen our community.',
    'give.livesTouched': 'Lives Touched',
    'give.livesText': 'Through our community outreach programs',
    'give.familiesSupported': 'Families Supported',
    'give.familiesText': 'With food, clothing, and assistance',
    'give.ministryPrograms': 'Ministry Programs',
    'give.programsText': 'Serving all ages in our community',
    'give.questions': 'Questions About Giving?',
    'give.questionsText': 'Our finance team is here to help with any questions about giving or donations.',
    
    // Sermons Page
    'sermons.title': 'Sermons',
    'sermons.subtitle': 'Listen to inspiring messages that will strengthen your faith and encourage your walk with God.',
    'sermons.featured': 'Featured Sermon',
    'sermons.allSermons': 'All Sermons',
    'sermons.search': 'Search sermons...',
    'sermons.speaker': 'Speaker',
    'sermons.series': 'Series',
    'sermons.duration': 'Duration',
    'sermons.watch': 'Watch',
    'sermons.listen': 'Listen',
    'sermons.download': 'Download',
    'sermons.share': 'Share',
    
    // Videos Page
    'videos.title': 'Videos',
    'videos.subtitle': 'Watch our latest services, events, and special messages.',
    'videos.watch': 'Watch Video',
    
    // Gallery Page
    'gallery.title': 'Photo Gallery',
    'gallery.subtitle': 'Celebrating moments of worship, fellowship, and community.',
    'gallery.filterByCategory': 'Filter by Category',
    'gallery.allPhotos': 'All Photos',
  },
  yo: {
    // Navigation
    'nav.home': 'Ilé',
    'nav.about': 'Nípa Wa',
    'nav.sermons': 'Àwọn Ìwàásù',
    'nav.videos': 'Àwọn Fídíò',
    'nav.gallery': 'Àwòrán',
    'nav.events': 'Àwọn Ìṣẹ̀lẹ̀',
    'nav.ministries': 'Àwọn Iṣẹ́ Ìjọ',
    'nav.contact': 'Kàn Sí Wa',
    'nav.admin': 'Alábòjútó',
    'nav.give': 'Fún Wa',
    'nav.tagline': 'Ìgbàgbọ́, Ìrètí àti Ìfẹ́.',
    
    // Footer
    'footer.quickLinks': 'Àwọn Ọ̀nà Yára',
    'footer.contact': 'Kàn Sí Wa',
    'footer.followUs': 'Tẹ̀lé Wa',
    'footer.serviceTimes': 'Àkókò Ìjọ́sìn',
    'footer.rights': 'Gbogbo ẹ̀tọ́ ni a dáàbò bò.',
    'footer.aboutUs': 'Nípa Wa',
    'footer.prayerRequests': 'Àwọn Ìbéèrè Àdúrà',
    'footer.sundayWorship': 'Ìjọ́sìn Ọjọ́ Àìkú: 8:00 AM - 10:00 AM',
    'footer.bibleStudy': 'Ìkẹ́kọ̀ọ́ Bíbélì Ọjọ́rú: 5:00 PM - 6:00PM',
    'footer.youthGroup': 'Ìdàpọ̀ Ẹgbẹ́ Ọ̀dọ́: Ọjọ́ Ẹtì 5:00 PM',
    'footer.address': '20, Michael Ibru Road, Amilegbe, P.O. Box 138, Ilorin, Nigeria.',
    
    // Common
    'common.readMore': 'Kà Síwájú',
    'common.register': 'Forúkọsílẹ̀',
    'common.submit': 'Fi Ránṣẹ́',
    'common.loading': 'Ń gbé...',
    'common.viewAll': 'Wo Gbogbo',
    'common.learnMore': 'Kọ́ Síi',
    'common.getInvolved': 'Kópa',
    'common.contactLeader': 'Kàn Sí Olórí',
    'common.sendMessage': 'Fi Ìkìlọ̀ Ránṣẹ́',
    'common.sending': 'Ń fi ránṣẹ́...',
    
    // Homepage
    'home.welcomeHome': 'Káàbọ̀ Sílé',
    'home.welcomeText': 'Níbi tí ìgbàgbọ́ ti ń dàgbà, àwọn ọkàn ń wó sàn, àti àwọn ìgbésí ayé ti ń yí padà nípasẹ̀ ìfẹ́ Ọlọ́run àti àwùjọ.',
    'home.watchLive': 'Wòó Láyé',
    'home.joinUsThisWeek': 'Dara pọ̀ mọ́ Wa Lọ́sẹ̀ Yìí',
    'home.joinUsText': 'Wá bí o ṣe wà kí o sì ní ìrírí ìfẹ́ Ọlọ́run nínú àwùjọ àbò wa.',
    'home.sundayWorship': 'Ìjọ́sìn Ọjọ́ Àìkú',
    'home.englishService': 'Ìjọ́sìn Gẹ̀ẹ́sì: 8:00AM - 10:00AM',
    'home.yorubaService': 'Ìjọ́sìn Yorùbá: 10:00AM - 12:00PM',
    'home.bibleStudy': 'Ìkẹ́kọ̀ọ́ Bíbélì',
    'home.bibleStudyTime': 'Ọjọ́rú 5:00 PM - 6:00PM',
    'home.bibleStudyText': 'Ìwádìí jíjìn sínú Ọ̀rọ̀ Ọlọ́run papọ̀',
    'home.youthGroup': 'Ẹgbẹ́ Ọ̀dọ́',
    'home.youthGroupTime': 'Ọjọ́ Ẹtì 5:00 PM',
    'home.youthGroupText': 'Ìgbádùn, ìgbàgbọ́, àti ìdàpọ̀ fún àwọn ọ̀dọ́',
    'home.ourHeartMission': 'Ọkàn àti Iṣẹ́ Àpinfunni Wa',
    'home.missionText1': 'Fún ọ̀pọ̀lọpọ̀ ọdún, Second ECWA ti jẹ́ ìmọ́lẹ̀ ìrètí àti ìfẹ́ nínú àwùjọ wa. A gbà pé agbára ìyípadà ti ìgbàgbọ́, agbára àwùjọ, àti pàtàkì ìsìn àwọn mìíràn pẹ̀lú àánú àti oore-ọ̀fẹ́.',
    'home.missionText2': 'Bóyá o ń wá ìtọ́sọ́nà ẹ̀mí, ń wá ibi tí o lè jẹ́ ti, tàbí fẹ́ṣe ìyàtọ̀ nínú ayé, ìwọ yóò rí ilé rẹ níhìn-ín pẹ̀lú wa.',
    'home.learnMore': 'Kọ́ Síi Nípa Wa',
    'home.members': '500+ Ọmọ Ẹgbẹ́',
    'home.growingTogether': 'Ń dàgbà nínú ìgbàgbọ́ papọ̀',
    'home.getConnected': 'Darapọ̀ Mọ́ Wa',
    'home.getConnectedText': 'Ṣàwárí àwọn ọ̀nà láti dàgbà nínú ìgbàgbọ́ àti sìn àwùjọ wa',
    'home.latestSermons': 'Àwọn Ìwàásù Tuntun',
    'home.latestSermonsText': 'Gbọ́ àwọn ìwàásù àìpẹ́ kí o sì rí ìmísí',
    'home.upcomingEvents': 'Àwọn Ìṣẹ̀lẹ̀ Tó Ń Bọ̀',
    'home.upcomingEventsText': 'Darapọ̀ mọ́ wa fún àwọn iṣẹ́ pàtàkì àti ìgbòkegbodò',
    'home.giveOnline': 'Fún Ní Orí Íńtánẹ́ẹ̀tì',
    'home.giveOnlineText': 'Ṣe àtìlẹ́yìn iṣẹ́ àpinfunni àti ìránṣẹ́ àwùjọ wa',
    'home.visitUs': 'Bẹ̀ Wá Wò',
    'home.visitUsText': 'Wá ọ̀nà àti gbèrò ìbẹ̀wò àkọ́kọ́ rẹ',
    'home.thisWeekMessage': 'Ìkìlọ̀ Ọ̀sẹ̀ Yìí',
    'home.featuredSermonTitle': '"Rìn Nínú Ìgbàgbọ́, Kì Í Ṣe Ẹ̀rù"',
    'home.featuredSermonText': 'Darapọ̀ mọ́ Samuel Oyegunle bí ó ṣe ń ṣàwárí bí ìgbàgbọ́ ṣe lè ṣẹ́gun àwọn ẹ̀rù wa tó jinlẹ̀ àti àìdánilójú. Ṣàwárí àlàáfíà tí ó ń wá láti gbẹ́kẹ̀lé ètò pípé Ọlọ́run fún ìgbésí ayé rẹ.',
    'home.scripture': 'Ìwé Mímọ́',
    'home.scriptureRef': 'Isaiah 41:10',
    'home.date': 'Ọjọ́',
    'home.sermonDate': 'May 15, 2025',
    'home.viewAllSermons': 'Wo Gbogbo Ìwàásù',
    'home.watchSermon': 'Wò Ìwàásù',
    
    // About Page
    'about.title': 'Nípa Second ECWA',
    'about.subtitle': 'Fún ọ̀pọ̀lọpọ̀ ọdún, a ti jẹ́ ibi tí ìgbàgbọ́ ti ń gbilẹ̀, àwùjọ ń gbòòrò, àti àwọn ìgbésí ayé ti ń yí padà nípasẹ̀ ìfẹ́ Jésù Kristi.',
    'about.ourStory': 'Ìtàn Wa',
    'about.storyText1': 'A dá Second ECWA sílẹ̀ ní ọdún 1974 látọwọ́ ẹgbẹ́ kékeré àwọn ológun tí wọ́n ní ìran láti dá ìjọ tí yóò jẹ́ ọkàn àwùjọ. Ohun tí ó bẹ̀rẹ̀ bí ìpàdé lọ́pọ̀lọpọ̀ nínú yàrá kan ti di ìjọ alágbára ti ó ju ọmọ ẹgbẹ́ 500 lọ.',
    'about.storyText2': 'Nígbà gbogbo ìtàn wa, a ti dúró ṣinṣin sí àwọn ìlànà ìpilẹ̀ṣẹ̀ wa: ìjọ́sìn òtítọ́, àwùjọ òtítọ́, àti iṣẹ́ àánú. A gbà pé ìgbàgbọ́ kì í ṣe iṣẹ́ àárọ̀ Ọjọ́ Àìkú nìkan, ṣùgbọ́n ọ̀nà ìgbésí ayé tí ó ń yi àwọn ẹni kọ̀ọ̀kan, àwọn ìdílé, àti àwọn àwùjọ padà.',
    'about.storyText3': 'Lónìí, a ń tẹ̀síwájú láti jẹ́ ibi tí àwọn ènìyàn láti gbogbo ìgbésí ayé lè rí ìrètí, ìwòsàn, àti ète. Bóyá o ń gbé ìgbésẹ̀ àkọ́kọ́ rẹ nínú ìgbàgbọ́ tàbí o ti ń rìn pẹ̀lú Ọlọ́run fún ọ̀pọ̀lọpọ̀ ọdún, ìwọ yóò rí ilé níhìn-ín pẹ̀lú wa.',
    'about.yearsOfMinistry': 'Ọdún Iṣẹ́ Ìjọ',
    'about.ourMission': 'Iṣẹ́ Àpinfunni Wa',
    'about.missionText': 'Láti jẹ́ ọkàn àwùjọ wa nípa sí so àwọn ènìyàn mọ́ Ọlọ́run, sí ara wọn, àti sí ète wọn nípasẹ̀ ìjọ́sìn òtítọ́, àjọṣe òtítọ́, àti iṣẹ́ àánú.',
    'about.ourVision': 'Ìran Wa',
    'about.visionText': 'Àwùjọ kan níbi tí gbogbo ènìyàn ti ń ní ìrírí ìfẹ́ ìyípadà Jésù Kristi àti tí wọ́n ti ní agbára láti ṣe ipa rere nínú ayé tí ó yí wọn ká.',
    'about.coreValues': 'Àwọn Iye Pàtàkì Wa',
    'about.coreValuesText': 'Àwọn iye wọ̀nyí ń ṣe ìtọ́sọ́nà gbogbo ohun tí a ń ṣe àti ṣe àpẹẹrẹ àṣà àwùjọ ìjọ wa.',
    'about.love': 'Ìfẹ́',
    'about.loveText': 'A gbàgbọ́ nínú agbára ìyípadà ti ìfẹ́ àìlábùkún Ọlọ́run àti a ń gbìyànjú láti pín in pẹ̀lú gbogbo ènìyàn tí a bá pàdé.',
    'about.community': 'Àwùjọ',
    'about.communityText': 'A ń ṣe ìgbékalẹ̀ àjọṣe òtítọ́ àti ṣẹ̀dá àyè àbò níbi tí gbogbo ènìyàn lè jẹ́ ti àti dàgbà papọ̀.',
    'about.service': 'Iṣẹ́',
    'about.serviceText': 'A pè wá láti sìn àwùjọ wa àti kọjá, láti ṣe ipa rere ní orúkọ Jésù.',
    'about.compassion': 'Àánú',
    'about.compassionText': 'A ń fi oore-ọ̀fẹ́ àti àánú hàn sí gbogbo ènìyàn, a ń fún ni pẹ̀lú àtìlẹ́yìn àti ìtọ́jú láìṣe ìdájọ́.',
    'about.leadership': 'Ẹgbẹ́ Olórí Wa',
    'about.leadershipText': 'Pàdé àwọn olórí tí wọ́n ní ìfọ̀kànsí tí wọ́n ń sìn àwùjọ ìjọ wa pẹ̀lú ìtara àti ète.',
    'about.whatWeBelieve': 'Ohun Tí A Gbàgbọ́',
    'about.faithGrounded': 'Ìgbàgbọ́ wa ti dá lé òtítọ́ àìlópin Kristẹ́nítì',
    'about.bible': 'Bíbélì',
    'about.bibleText': 'A gbàgbọ́ pé Bíbélì jẹ́ Ọ̀rọ̀ Ọlọ́run tí ó ní àmì-atọ̀, tí ó ní àṣẹ àti ìtọ́sọ́nà wa fún ìgbàgbọ́ àti ìgbésí ayé.',
    'about.jesusChrist': 'Jésù Kristi',
    'about.jesusText': 'A gbàgbọ́ pé Jésù Kristi ni Ọmọ Ọlọ́run, tí ó kú fún ẹ̀ṣẹ̀ wa tí ó sì jíǹde, tí ó ń fún ni pẹ̀lú ìgbàlà fún gbogbo àwọn tí ó gbàgbọ́.',
    'about.holySpirit': 'Ẹ̀mí Mímọ́',
    'about.spiritText': 'A gbàgbọ́ pé Ẹ̀mí Mímọ́ ń ṣe ìtọ́sọ́nà, fún ni ní agbára, àti yí àwọn onígbàgbọ́ padà láti gbé ìgbésí ayé gẹ́gẹ́ bí ìfẹ́ Ọlọ́run.',
    'about.church': 'Ìjọ',
    'about.churchText': 'A gbàgbọ́ pé ìjọ ni ara Kristi, tí a pè láti jọ́sìn Ọlọ́run, ṣe ìdàpọ̀ papọ̀, àti sìn ayé.',
    
    // Events Page
    'events.title': 'Àwọn Ìṣẹ̀lẹ̀ Tó Ń Bọ̀',
    'events.subtitle': 'Darapọ̀ mọ́ wa fún àwọn ìpàdé tó ní ìtumọ̀, àwọn iṣẹ́ pàtàkì, àti àwọn ìṣẹ̀lẹ̀ àwùjọ tí ń mú ìgbàgbọ́ àti ìdàpọ̀ wa le.',
    'events.featured': 'Ìṣẹ̀lẹ̀ Pàtàkì',
    'events.featuredText': 'Má ṣe gbàgbé ìṣẹ̀lẹ̀ pàtàkì yìí tó ń bọ̀',
    'events.register': 'Forúkọsílẹ̀ Báyìí',
    'events.allEvents': 'Gbogbo Ìṣẹ̀lẹ̀',
    'events.filterByCategory': 'Ṣàlò Gẹ́gẹ́ bí Ẹka',
    'events.registered': 'forúkọsílẹ̀',
    'events.firstName': 'Orúkọ Àkọ́kọ́',
    'events.lastName': 'Orúkọ Ìdílé',
    'events.email': 'Ímeèlì',
    'events.phone': 'Fóònù',
    'events.specialNeeds': 'Àwọn Ìlò Pàtàkì/Ìrànwọ́',
    'events.emergencyContact': 'Olùbásọ̀rọ̀ Ìpayà',
    'events.emergencyPhone': 'Fóònù Ìpayà',
    'events.completeRegistration': 'Parí Ìforúkọsílẹ̀',
    'events.registering': 'Ń forúkọsílẹ̀...',
    
    // Ministries Page
    'ministries.title': 'Àwọn Iṣẹ́ Ìjọ Wa',
    'ministries.subtitle': 'Ṣàwárí àwọn ọ̀nà láti dàgbà nínú ìgbàgbọ́, kọ́ àwùjọ, àti sìn àwọn mìíràn. Ibi kan wà fún gbogbo ènìyàn láti jẹ́ ti àti ṣe ìyàtọ̀.',
    'ministries.featured': 'Iṣẹ́ Ìjọ Pàtàkì',
    'ministries.featuredText': 'Kópa kí o sì ṣe ipa tó ní ìtumọ̀',
    'ministries.ageGroup': 'Ẹgbẹ́ Ọjọ́-orí',
    'ministries.meetingTime': 'Àkókò Ìpàdé',
    'ministries.location': 'Ibi',
    'ministries.leader': 'Olórí',
    'ministries.activities': 'Àwọn Iṣẹ́',
    'ministries.allMinistries': 'Gbogbo Iṣẹ́ Ìjọ',
    'ministries.allMinistriesText': 'Láti ọmọdé sí àgbàlagbà, láti ìjọ́sìn sí ìránṣẹ́, wá ibi tí o lè sìn àti dàgbà nínú ìrìnàjò ìgbàgbọ́ rẹ.',
    'ministries.volunteer': 'Yọ̀ǹda Láti Ran Wá Lọ́wọ́',
    'ministries.position': 'Ipò/Ipa Tí O Fẹ́',
    'ministries.volunteerApplication': 'Fi Ìbéèrè Yọ̀ǹda Ránṣẹ́',
    'ministries.submitting': 'Ń fi ránṣẹ́...',
    
    // Contact Page
    'contact.title': 'Kàn Sí Wa',
    'contact.subtitle': 'A fẹ́ gbọ́ tìrẹ! Bóyá o ní àwọn ìbéèrè, nílò àdúrà, tàbí fẹ́ kópa, a wà níbí láti ran ọ́ lọ́wọ́.',
    'contact.address': 'Àdírẹ́ẹ̀sì',
    'contact.phone': 'Fóònù',
    'contact.email': 'Ímeèlì',
    'contact.openHours': 'Àwọn Wákàtí Ṣíṣí',
    'contact.serviceSchedule': 'Àtòjọ Ìjọ́sìn',
    'contact.scheduleText': 'Darapọ̀ mọ́ wa fún ìjọ́sìn àti ìdàpọ̀ ní gbogbo ọ̀sẹ̀',
    'contact.sendMessage': 'Fi Ìkìlọ̀ Ránṣẹ́ Sí Wa',
    'contact.messageText': 'Ṣé o ní ìbéèrè tàbí ìbéèrè àdúrà? A fẹ́ gbọ́ tìrẹ. Kún fọ́ọ̀mù tó wà nísàlẹ̀ yìí kí a sì padà sí ọ bí o ṣe yára tó.',
    'contact.subject': 'Kókó',
    'contact.message': 'Ìkìlọ̀',
    'contact.findUs': 'Wá Wa',
    'contact.mapText': 'Ṣé o rí mápù náà?',
    'contact.openInGoogleMaps': 'Ṣí Nínú Google Maps',
    'contact.needPrayer': 'Ṣé O Nílò Àdúrà?',
    'contact.prayerText': 'Ẹgbẹ́ àdúrà wa wà níbí fún ọ. Fi ìbéèrè àdúrà ìkọ̀kọ̀ ránṣẹ́ kí o sì mọ̀ pé àwùjọ wa ń gbé ọ sókè nínú àdúrà.',
    'contact.prayerRequest': 'Ìbéèrè Àdúrà',
    'contact.urgent': 'Èyí jẹ́ kíákíá',
    'contact.confidential': 'Jẹ́ kí èyí jẹ́ ìkọ̀kọ̀',
    'contact.submitPrayer': 'Fi Ìbéèrè Àdúrà Ránṣẹ́',
    'contact.submittingPrayer': 'Ń fi ránṣẹ́...',
    
    // Give Page
    'give.title': 'Fún Pẹ̀lú Ète',
    'give.subtitle': 'Oore-ọ̀fẹ́ rẹ ń ran wá lọ́wọ́ láti mú iṣẹ́ àpinfunni wa ṣẹ láti tan ìfẹ́ Ọlọ́run àti sin àwùjọ wa pẹ̀lú àánú àti ìtọ́jú.',
    'give.scripture': '"Ẹnìkọ̀ọ̀kan yín gbọdọ̀ fún gẹ́gẹ́ bí ó ṣe pinnu nínú ọkàn rẹ̀, kì í ṣe pẹ̀lú ìkọ̀sílẹ̀ tàbí nípasẹ̀ ìfipá, nítorí Ọlọ́run fẹ́ràn olùfúnni alárìnká."',
    'give.scriptureRef': '- 2 Kọríńtì 9:7',
    'give.waysToGive': 'Àwọn Ọ̀nà Láti Fún',
    'give.waysText': 'Yan ọ̀nà ìfúnni tí ó bá múdọ́gba pẹ̀lú ọkàn àti ipò owó rẹ.',
    'give.tithe': 'Ìdámẹ́wàá',
    'give.titheText': 'Ìfúnni déédéé láti ṣe àtìlẹ́yìn iṣẹ́ ìjọ',
    'give.titheAmount': '10% ti èrè',
    'give.specialOffering': 'Ọrẹ Pàtàkì',
    'give.offeringText': 'Ṣe àtìlẹ́yìn àwọn iṣẹ́ pàtàkì àti àwọn ìránṣẹ́',
    'give.buildingFund': 'Owó Ilé',
    'give.buildingText': 'Ran wá lọ́wọ́ láti fẹ̀ àwọn ohun èlò ìjọ wa',
    'give.anyAmount': 'Iye owó èyíkéyìí',
    'give.howToGive': 'Bí O Ṣe Lè Fún',
    'give.methodsText': 'Yan ọ̀nà tí o fẹ́ láti fi ọrẹ rẹ fún.',
    'give.bankTransfer': 'Gbígbé Owó Bánkì',
    'give.bankText': 'Gbígbé owó táárá sí àkọọ́lẹ̀ bánkì ìjọ wa',
    'give.onlineDonation': 'Ọrẹ Lórí Íńtánẹ́ẹ̀tì',
    'give.onlineText': 'Ìfúnni tó wà láìléwu nípasẹ̀ Paystack',
    'give.giveOnlineButton': 'Fún Lórí Íńtánẹ́ẹ̀tì (Ń Bọ̀ Láìpẹ́)',
    'give.yourImpact': 'Ipa Rẹ',
    'give.impactText': 'Wo bí ìfúnni oore-ọ̀fẹ́ rẹ ṣe ń ran àwọn ìgbésí ayé lọ́wọ́ láti yí padà àti mú àwùjọ wa le.',
    'give.livesTouched': 'Àwọn Ìgbésí Ayé Tí A Fọwọ́ Kàn',
    'give.livesText': 'Nípasẹ̀ àwọn ètò ìránṣẹ́ àwùjọ wa',
    'give.familiesSupported': 'Àwọn Ìdílé Tí A Ṣe Àtìlẹ́yìn',
    'give.familiesText': 'Pẹ̀lú oúnjẹ, aṣọ, àti ìrànwọ́',
    'give.ministryPrograms': 'Àwọn Ètò Iṣẹ́ Ìjọ',
    'give.programsText': 'Sísìn gbogbo ọjọ́-orí nínú àwùjọ wa',
    'give.questions': 'Àwọn Ìbéèrè Nípa Ìfúnni?',
    'give.questionsText': 'Ẹgbẹ́ owó wa wà níbí láti ran ọ́ lọ́wọ́ pẹ̀lú ìbéèrè èyíkéyìí nípa ìfúnni tàbí àwọn ọrẹ.',
    
    // Sermons Page
    'sermons.title': 'Àwọn Ìwàásù',
    'sermons.subtitle': 'Gbọ́ àwọn ìkìlọ̀ ìmísí tí yóò mú ìgbàgbọ́ rẹ le àti ṣe ìwúlò fún ìrìnàjò rẹ pẹ̀lú Ọlọ́run.',
    'sermons.featured': 'Ìwàásù Pàtàkì',
    'sermons.allSermons': 'Gbogbo Ìwàásù',
    'sermons.search': 'Wá àwọn ìwàásù...',
    'sermons.speaker': 'Agbẹnusọ',
    'sermons.series': 'Jára',
    'sermons.duration': 'Ìgbà',
    'sermons.watch': 'Wò',
    'sermons.listen': 'Gbọ́',
    'sermons.download': 'Ṣe Ìgbàsílẹ̀',
    'sermons.share': 'Pín',
    
    // Videos Page
    'videos.title': 'Àwọn Fídíò',
    'videos.subtitle': 'Wò àwọn iṣẹ́ àìpẹ́ wa, àwọn ìṣẹ̀lẹ̀, àti àwọn ìkìlọ̀ pàtàkì.',
    'videos.watch': 'Wò Fídíò',
    
    // Gallery Page
    'gallery.title': 'Àwòrán Àwòkọ́ṣe',
    'gallery.subtitle': 'Ṣíṣe àjọyọ̀ àwọn ìṣẹ̀jú ìjọ́sìn, ìdàpọ̀, àti àwùjọ.',
    'gallery.filterByCategory': 'Ṣàlò Gẹ́gẹ́ bí Ẹka',
    'gallery.allPhotos': 'Gbogbo Àwòrán',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};